//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows8Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computer
    {
        public int Id { get; set; }
        public ComputerType Type { get; set; }
    
        public virtual Brand Brand { get; set; }
    }
}
