//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows8Store.Models
{
    using System;
    
    public enum ComputerType : int
    {
        Desktop = 0,
        Laptop = 1,
        Tablet = 2,
        Smartphone = 3
    }
}
